/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddLPInterestItemPane.java
 *
 * Created on 2011-1-6, 10:43:19
 */
package lp.interest;

import java.awt.Color;
import lp.LPApp;
import util.Constant;
import util.LogConstant;

/**
 *
 * @author william
 */
public class AddLPInterestItemPane extends javax.swing.JPanel {

    public UserInterestPane parent;
    private Color backgroundColor;
    public ontology.EConcept concept;
    public java.awt.Color mouseEnteredColor;
    public javax.swing.Icon icon;

    public static void main(String[] args) {
//        jena.impl.ELearnerModelImpl emi = new jena.impl.ELearnerModelImpl(new java.io.File("test\\owl\\conceptsAndresource_RDF-XML.owl"));
//        ontology.people.ELearner el = emi.getELearner("el001");
//        //java.util.ArrayList<ontology.EInterest> interests = emi.getEInterests(el);
//        java.util.ArrayList<ontology.EConcept> concepts = jena.ELearnerReasoner.getRecommendEConcepts_1(emi.getOntModel(), el);
//        // System.out.println(interests);
//        javax.swing.JFrame frame = new javax.swing.JFrame();
//        // LPListPane lppane = new LPListPane(interests);
//        javax.swing.JPanel pane = new javax.swing.JPanel();
//        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
//        pane.setLayout(new javax.swing.BoxLayout(pane, javax.swing.BoxLayout.Y_AXIS));
//        for (int i = 0; i < concepts.size(); i++) {
//            AddLPInterestItemPane p = new AddLPInterestItemPane(pane,concepts.get(i));
//            pane.add(p);
//        }
//        frame.add(pane);
//        frame.pack();
//        frame.setVisible(true);
    }

    /** Creates new form AddLPInterestItemPane */
    public AddLPInterestItemPane(UserInterestPane parent) {
        initComponents();
        myInit(parent);
    }

    public AddLPInterestItemPane(UserInterestPane parent, ontology.EConcept concept) {
        this.concept = concept;
        initComponents();
        myInit(parent);
    }

    private void myInit(UserInterestPane parent) {
        this.parent = parent;
        mouseEnteredColor = new java.awt.Color(255, 255, 255);
        jLabel3.setIcon(null);
        jLabel2.setText(concept.getName());
        backgroundColor = Constant.backgroundGrayColor;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(430, 35));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addItemMouseExited(evt);
            }
        });

        jLabel2.setText("jLabel2");
        jLabel2.setMinimumSize(null);
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(395, 35));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lp/interest/resources/+.png"))); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(35, 35));
        icon =new javax.swing.ImageIcon(getClass().getResource("/lp/interest/resources/+.png"));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addInterestItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void displayWhiteShade() {
        jLabel3.setIcon(icon);
        this.setBackground(mouseEnteredColor);
        jLabel2.setBackground(mouseEnteredColor);
        jLabel3.setBackground(mouseEnteredColor);
        this.updateUI();
    }

    private void hideWhiteShade() {
        jLabel3.setIcon(null);
        this.setBackground(backgroundColor);
        jLabel2.setBackground(backgroundColor);
        jLabel3.setBackground(backgroundColor);
        this.updateUI();
    }

    private void addItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemMouseEntered
        displayWhiteShade();
    }//GEN-LAST:event_addItemMouseEntered

    private void addItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemMouseExited
        hideWhiteShade();
    }//GEN-LAST:event_addItemMouseExited

    private void addInterestItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addInterestItemMouseClicked
        System.out.println("add interest item clicked");
        parent.addInterest(this);
        LPApp.lpLogs.writeLog( "添加知识点:"+concept.getCid() + " " + concept.getName(), LogConstant.STATUS109);
    }//GEN-LAST:event_addInterestItemMouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        b1 = true;
        displayWhiteShade();
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        b1 = true;
        displayWhiteShade();
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        b1 = false;
        if (b1 || b2) {
            displayWhiteShade();
        } else {
            hideWhiteShade();
        }
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        b2 = false;
        if (b1 || b2) {
            displayWhiteShade();
        } else {
            hideWhiteShade();
        }
    }//GEN-LAST:event_jLabel3MouseExited
    private boolean b1 = false;
    private boolean b2 = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
