/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserInterestPane.java
 *
 * Created on 2011-1-11, 0:09:05
 */
package lp.interest;

import com.hp.hpl.jena.ontology.OntModel;
import exception.jena.IndividualExistException;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import jena.impl.ELearnerModelImpl;
import lp.LPApp;
import lp.log.PopMesDialog;
import ontology.EConcept;
import ontology.EInterest;
import ontology.people.ELearner;
import util.LogConstant;

/**
 *
 * @author william
 */
public class UserInterestPane extends javax.swing.JPanel {

    private ArrayList<EInterest> interests;
    private ArrayList<EConcept> concepts;
    private ELearner elearner;
    private int randomInt;

    public static void main(String[] args) {
//        ELearnerModelImpl emi = new ELearnerModelImpl();
//        ELearner el = emi.getELearner("el001");
//        ArrayList<EInterest> interests = emi.getEInterests(el);
//        ArrayList<EConcept> concepts = jena.ELearnerReasoner.getRecommendEConcepts_1(emi.getOntModel(), el);
//        javax.swing.JFrame f = new javax.swing.JFrame();
//        UserInterestPane uip = new UserInterestPane(interests, concepts);
//        f.add(uip);
//        f.pack();
//        f.setVisible(true);
        Random ran = new Random();
        for (int i = 0; i < 10; i++) {
            int ranInt = ran.nextInt(4);
            System.out.println("ran\t" + ranInt);
        }


    }

    /** Creates new form UserInterestPane */
    public UserInterestPane() {
        initComponents();
        initInterestPane(new ArrayList<EInterest>(), new ArrayList<EConcept>());
    }

    public UserInterestPane(ArrayList<EInterest> interests, ArrayList<EConcept> concepts) {
        initComponents();
        initInterestPane(interests, concepts);
    }

    public void updateInterests(ArrayList<EInterest> interests, ArrayList<EConcept> concpets) {
        System.out.println("to be implmented");
    }
    // update the uninterest pane

    public void updateUnInterets(ArrayList<EConcept> concept) {
        concepts.removeAll(concept);
        concepts = concept;
    }

    public void removeInterest(RemoveLPInterestItemPane removeInterestItem) {
        System.out.println("HH:" + removeInterestItem.interest);
        System.out.println("size:" + interests.size());
        interests.remove(removeInterestItem.interest);
        interestPane.remove(removeInterestItem);

        concepts.add(removeInterestItem.interest.getEConcept());
        unInterestPane.add(new AddLPInterestItemPane(this, removeInterestItem.interest.getEConcept()));
        interestPane.updateUI();
    }

    public void addInterest(AddLPInterestItemPane addInterestItem) {
        EConcept con = addInterestItem.concept;
        EInterest interest = new EInterest();
        interest.setValue(0.5f);
        interest.setEConcept(con);
        interest.setELearner(elearner);
        interest.setId(elearner.getId() + con.getCid());
        interestPane.add(new RemoveLPInterestItemPane(this, interest));
        interests.add(interest);

        concepts.remove(con);
        unInterestPane.remove(addInterestItem);
        interestPane.updateUI();
    }

    private void initInterestPane(ArrayList<ontology.EInterest> interests, ArrayList<ontology.EConcept> concepts) {
        this.interests = interests;
        this.concepts = concepts;
        randomInt = 0;
        elearner = LPApp.getApplication().user.learner;
        interestPane.setLayout(new javax.swing.BoxLayout(interestPane, javax.swing.BoxLayout.Y_AXIS));
        for (int i = 0; i < interests.size(); i++) {
            RemoveLPInterestItemPane p = new RemoveLPInterestItemPane(this, interests.get(i));
            interestPane.add(p);
        }
        unInterestPane.setLayout(new javax.swing.BoxLayout(unInterestPane, javax.swing.BoxLayout.Y_AXIS));
        for (int i = 0; i < concepts.size(); i++) {
            AddLPInterestItemPane p = new AddLPInterestItemPane(this, concepts.get(i));
            unInterestPane.add(p);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        interestPane = new javax.swing.JPanel();
        unInterestPane = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addInterestText = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(430, 527));

        interestPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "有兴趣的知识点", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 1, 14))); // NOI18N
        interestPane.setName("interestPane"); // NOI18N
        interestPane.setPreferredSize(new java.awt.Dimension(430, 248));

        javax.swing.GroupLayout interestPaneLayout = new javax.swing.GroupLayout(interestPane);
        interestPane.setLayout(interestPaneLayout);
        interestPaneLayout.setHorizontalGroup(
            interestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        interestPaneLayout.setVerticalGroup(
            interestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        unInterestPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "您可能感兴趣的知识点", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 1, 14))); // NOI18N
        unInterestPane.setName("unInterestPane"); // NOI18N
        unInterestPane.setPreferredSize(new java.awt.Dimension(416, 248));

        javax.swing.GroupLayout unInterestPaneLayout = new javax.swing.GroupLayout(unInterestPane);
        unInterestPane.setLayout(unInterestPaneLayout);
        unInterestPaneLayout.setHorizontalGroup(
            unInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        unInterestPaneLayout.setVerticalGroup(
            unInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        jButton3.setText("添加兴趣");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jButton1.setText("换 一 换 兴 趣");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addInterestText.setText("输入感兴趣的概念");
        addInterestText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addInterestTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(addInterestText, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(unInterestPane, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
            .addComponent(interestPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(interestPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addInterestText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unInterestPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addInterestTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addInterestTextMouseClicked
        if (evt.getClickCount() == 2) {
            addInterestText.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addInterestTextMouseClicked

    //add interest concept for the current elearner
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String name = addInterestText.getText();
        if (name != null) {
            ArrayList<String> cids = LPApp.lpModel.getConceptIds(name);
            if (cids.isEmpty()) {
                PopMesDialog pop = new PopMesDialog();
                pop.setTitle("查询不到");
                pop.setMessage("知识点没找到，请重新输入");
                LPApp.lpLogs.writeLog(109, name, "不存在知识点", LogConstant.STATUS109);
                System.out.println("concept not exist");
            } else {
                System.out.println("get the name");
                LPApp.lpLogs.writeLog(109, name, "手动添加兴趣知识点", LogConstant.STATUS109);

                for (int i = 0; i < cids.size(); i++) {
                    String conceptId = cids.get(i);
                    EConcept con = LPApp.lpModel.getEConcept(conceptId);
                    EInterest in = new EInterest();
                    in.setId(LPApp.getApplication().user.learner.getId() + "_" + conceptId);
                    in.setEConcept(con);
                    in.setELearner(LPApp.getApplication().user.learner);
                    in.setValue(0.5f);
                    
                    LPApp.lpModel.addEInterest(in);
                    interestPane.add(new RemoveLPInterestItemPane(this, in));
                    interests.add(in);
                    interestPane.updateUI();
                    if (concepts.contains(con)) {
                        concepts.remove(con);
                        Component cs[] = unInterestPane.getComponents();
                        for (Component c : cs) {
                            AddLPInterestItemPane a = (AddLPInterestItemPane) c;
                            if (a.concept.getCid().equals(conceptId)) {
                                unInterestPane.remove(a);
                            }
                        }
                    }

                }
            }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<EConcept> unInterestsConcept = new ArrayList<EConcept>();
        ELearner el = LPApp.getApplication().user.learner;
        OntModel model = LPApp.lpModel.getOntModel();
        Random ran = new Random();
        int ranInt = 0;
        while (randomInt == ranInt) {
            ranInt = ran.nextInt(3);
        }
        randomInt = ranInt;

        switch (ranInt) {
            case 0:
                unInterestsConcept = jena.ELearnerReasoner.getRecommendEConcepts_1(model, el);
                break;
            case 1:
                unInterestsConcept = jena.ELearnerReasoner.getRecommendEConcepts_2(model, el);
                break;
            case 2:
                unInterestsConcept = jena.ELearnerReasoner.getRecommendEConcepts_4(model, el);
                break;
            default:
                unInterestsConcept = jena.ELearnerReasoner.getRecommendEConcepts_1(model, el);
        }
//        System.out.println("un:" + unInterestsConcept.size());

        unInterestPane.removeAll();
        if (unInterestsConcept.size() < 10) {
            for (int i = 0; i < unInterestsConcept.size(); i++) {
                AddLPInterestItemPane p = new AddLPInterestItemPane(this, unInterestsConcept.get(i));
                unInterestPane.add(p);
            }
        } else {
            for (int i = 0; i < 7; i++) {
                AddLPInterestItemPane p = new AddLPInterestItemPane(this, unInterestsConcept.get(i));
                unInterestPane.add(p);
            }
        }

        this.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addInterestText;
    private javax.swing.JPanel interestPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel unInterestPane;
    // End of variables declaration//GEN-END:variables
}
