/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserInterestPane.java
 *
 * Created on 2011-1-11, 0:09:05
 */
package lp.interest;

import java.util.ArrayList;
import jena.impl.ELearnerModelImpl;
import lp.LPApp;
import ontology.EConcept;
import ontology.EInterest;
import ontology.people.ELearner;

/**
 *
 * @author william
 */
public class UserInterestPane extends javax.swing.JPanel {

    private ArrayList<EInterest> interests;
    private ArrayList<EConcept> concepts;
private ELearner elearner = new ELearner("el001");
    public static void main(String[] args) {
        ELearnerModelImpl emi = new ELearnerModelImpl();
        ELearner el = emi.getELearner("el001");
        ArrayList<EInterest> interests = emi.getEInterests(el);
        ArrayList<EConcept> concepts = jena.ELearnerReasoner.getRecommendEConcepts_1(emi.getOntModel(), el);
        javax.swing.JFrame f = new javax.swing.JFrame();
        UserInterestPane uip = new UserInterestPane(interests, concepts);
        f.add(uip);
        f.pack();
        f.setVisible(true);
    }

    /** Creates new form UserInterestPane */
    public UserInterestPane() {
        initComponents();
        initInterestPane(new ArrayList<EInterest>(), new ArrayList<EConcept>());
    }

    public UserInterestPane(ArrayList<EInterest> interests, ArrayList<EConcept> concepts) {
        initComponents();
        initInterestPane(interests, concepts);
    }

    public void updateInterests(ArrayList<EInterest> interests, ArrayList<EConcept> concepts) {
        System.out.println("to be implmented");
    }

    public void addInterets(ArrayList<EConcept> concept) {

    }

    public void removeInterest(RemoveLPInterestItemPane removeInterestItem) {
        System.out.println("HH:" + removeInterestItem.interest);
        System.out.println("size:" + interests.size());
        interests.remove(removeInterestItem.interest);
        interestPane.remove(removeInterestItem);

        concepts.add(removeInterestItem.interest.getEConcept());
        unInterestPane.add(new AddLPInterestItemPane(this,removeInterestItem.interest.getEConcept()));
        interestPane.updateUI();
    }

    public void addInterest(AddLPInterestItemPane addInterestItem) {
        EConcept con = addInterestItem.concept;
        EInterest interest = new EInterest();
        interest.setValue(0.5f);
        interest.setEConcept(con);
        interest.setELearner(elearner);
        interest.setId(elearner.getId()+con.getCid());
        interestPane.add(new RemoveLPInterestItemPane(this,interest));
        interests.add(interest);

        concepts.remove(con);
        unInterestPane.remove(addInterestItem);
        interestPane.updateUI();
    }

    private void initInterestPane(ArrayList<ontology.EInterest> interests, ArrayList<ontology.EConcept> concepts) {
        this.interests = interests;
        this.concepts = concepts;
        interestPane.setLayout(new javax.swing.BoxLayout(interestPane, javax.swing.BoxLayout.Y_AXIS));
        for (int i = 0; i < interests.size(); i++) {
            RemoveLPInterestItemPane p = new RemoveLPInterestItemPane(this, interests.get(i));
            interestPane.add(p);
        }
        unInterestPane.setLayout(new javax.swing.BoxLayout(unInterestPane, javax.swing.BoxLayout.Y_AXIS));
        for (int i = 0; i < concepts.size(); i++) {
            AddLPInterestItemPane p = new AddLPInterestItemPane(this,concepts.get(i));
            unInterestPane.add(p);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        interestPane = new javax.swing.JPanel();
        unInterestPane = new javax.swing.JPanel();
        addInterestText = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(430, 625));

        interestPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "有兴趣的概念", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        interestPane.setName("interestPane"); // NOI18N

        javax.swing.GroupLayout interestPaneLayout = new javax.swing.GroupLayout(interestPane);
        interestPane.setLayout(interestPaneLayout);
        interestPaneLayout.setHorizontalGroup(
            interestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        interestPaneLayout.setVerticalGroup(
            interestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        unInterestPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "未感兴趣的概念", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        unInterestPane.setName("unInterestPane"); // NOI18N

        javax.swing.GroupLayout unInterestPaneLayout = new javax.swing.GroupLayout(unInterestPane);
        unInterestPane.setLayout(unInterestPaneLayout);
        unInterestPaneLayout.setHorizontalGroup(
            unInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        unInterestPaneLayout.setVerticalGroup(
            unInterestPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        addInterestText.setText("输入感兴趣的概念");
        addInterestText.setName("addInterestText"); // NOI18N
        addInterestText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addInterestTextMouseClicked(evt);
            }
        });

        jButton3.setText("添加兴趣");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interestPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unInterestPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(addInterestText, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(interestPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(unInterestPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(addInterestText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addInterestTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addInterestTextMouseClicked
        if (evt.getClickCount() == 2) {
            addInterestText.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addInterestTextMouseClicked

    //add interest concept for the current elearner
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String name = addInterestText.getText();
        if (name != null) {
            ArrayList<String> cids = LPApp.lpModel.getConceptIds(name);
            if (cids.isEmpty()) {
                System.out.println("concept not exist");
            } else {
                System.out.println("get the name");
            }

        }
    }//GEN-LAST:event_jButton3MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addInterestText;
    private javax.swing.JPanel interestPane;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel unInterestPane;
    // End of variables declaration//GEN-END:variables
}
