/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RadarPanelTwo.java
 *
 * Created on 2011-3-7, 10:20:52
 */

package lp.eresource;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Line2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSlider;
/**
 *
 * @author t
 */
public class RadarPanelTwo extends javax.swing.JPanel {

    /** Creates new form RadarPanelTwo */
     public RadarPanelTwo() {
        initComponents();
        for (int i = 0; i < 6; i++) {
                mx1[i] = cx - 0.25 * (cx - x[i]);
                my1[i] = cy - 0.25 * (cy - y[i]);
                mx2[i] = cx - 0.5 * (cx - x[i]);
                my2[i] = cy - 0.5 * (cy - y[i]);
                mx3[i] = cx - 0.75 * (cx - x[i]);
                my3[i] = cy - 0.75 * (cy - y[i]);
        }
    }
    private double tp = 150.0 / Math.sqrt(3);
    private double[] x = {56, 56, 206, 356, 356, 206};
    private double[] y = {550 - 3 * tp, 550 - tp, 550, 550 - tp, 550 - tp * 3, 550 - tp * 4};
    double[] mx1 = new double[6], my1 = new double[6], mx2 = new double[6], my2 = new double[6], mx3 = new double[6], my3 = new double[6];
    private static BasicStroke B_STROKE = new BasicStroke(2.0f);
    private static BasicStroke R_STROKE = new BasicStroke(5.0f);
    private static BasicStroke D_STROKE = new BasicStroke(1.5f,
                                                        BasicStroke.CAP_BUTT,
                                                        BasicStroke.JOIN_ROUND,
                                                        6.0f,
                                                        new float[] {3.0f, 3.0f},
                                                        1.5f);
    private double cx = 206, cy = 550 - 2 * tp;

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2d = (Graphics2D) g;

        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2d.setColor(Color.red);
        g2d.setStroke(B_STROKE);

        for (int i = 0; i < 5; i++) {
            g2d.draw(new Line2D.Double(x[i], y[i], x[i + 1], y[i + 1]));
        }
        g2d.draw(new Line2D.Double(x[5], y[5], x[0], y[0]));

        g2d.setStroke(D_STROKE);

        for (int i = 0; i < 5; i++) {
            g2d.draw(new Line2D.Double(cx, cy, x[i], y[i]));
            g2d.draw(new Line2D.Double(mx1[i], my1[i], mx1[i + 1], my1[i + 1]));
            g2d.draw(new Line2D.Double(mx2[i], my2[i], mx2[i + 1], my2[i + 1]));
            g2d.draw(new Line2D.Double(mx3[i], my3[i], mx3[i + 1], my3[i + 1]));
        }
        g2d.draw(new Line2D.Double(cx, cy, x[5], y[5]));
        g2d.draw(new Line2D.Double(mx1[5], my1[5], mx1[0], my1[0]));
        g2d.draw(new Line2D.Double(mx2[5], my2[5], mx2[0], my2[0]));
        g2d.draw(new Line2D.Double(mx3[5], my3[5], mx3[0], my3[0]));

        g2d.setColor(Color.black);
        g2d.setStroke(R_STROKE);

        double[] nx = new double[6];
        double[] ny = new double[6];
        JSlider[] sa = {jSlider1, jSlider2, jSlider3, jSlider4, jSlider5, jSlider6};
        for (int i = 0; i < 6; i++) {
                JSlider s = sa[i];
                nx[i] = cx - s.getValue() / 100.0 * (cx - x[i]);
                ny[i] = cy - s.getValue() / 100.0 * (cy - y[i]);
        }

        for (int i = 0; i < 5; i++) {
            g2d.draw(new Line2D.Double(nx[i], ny[i], nx[i + 1], ny[i + 1]));
        }
        g2d.draw(new Line2D.Double(nx[5], ny[5], nx[0], ny[0]));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jSlider5 = new javax.swing.JSlider();
        jSlider6 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jLabel1.setText("概念掌握");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jLabel2.setText("难点理解");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jLabel3.setText("实践能力");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jLabel4.setText("扩展学习");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jLabel5.setText("作业评估");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 14));
        jLabel6.setText("创新培养");
        jLabel6.setName("jLabel6"); // NOI18N

        jSlider1.setName("jSlider1"); // NOI18N
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1repaintRadar(evt);
            }
        });

        jSlider2.setName("jSlider2"); // NOI18N
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2repaintRadar(evt);
            }
        });

        jSlider3.setName("jSlider3"); // NOI18N
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3repaintRadar(evt);
            }
        });

        jSlider4.setName("jSlider4"); // NOI18N
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4repaintRadar(evt);
            }
        });

        jSlider5.setName("jSlider5"); // NOI18N
        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider5repaintRadar(evt);
            }
        });

        jSlider6.setName("jSlider6"); // NOI18N
        jSlider6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider6repaintRadar(evt);
            }
        });

        jButton1.setText("返回");
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setText("提交");
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider6, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(jSlider5, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(jSlider4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(jSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1repaintRadar(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1repaintRadar
        this.repaint();
}//GEN-LAST:event_jSlider1repaintRadar

    private void jSlider2repaintRadar(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2repaintRadar
        this.repaint();
}//GEN-LAST:event_jSlider2repaintRadar

    private void jSlider3repaintRadar(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3repaintRadar
        this.repaint();
}//GEN-LAST:event_jSlider3repaintRadar

    private void jSlider4repaintRadar(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4repaintRadar
        this.repaint();
}//GEN-LAST:event_jSlider4repaintRadar

    private void jSlider5repaintRadar(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider5repaintRadar
        this.repaint();
}//GEN-LAST:event_jSlider5repaintRadar

    private void jSlider6repaintRadar(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider6repaintRadar
        this.repaint();
}//GEN-LAST:event_jSlider6repaintRadar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    // End of variables declaration//GEN-END:variables

}
