/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResourceDetailPane.java
 *
 * Created on 2011-1-18, 15:39:42
 */
package lp.eresource;

import db.WebOperation;
import jena.impl.ELearnerModelImpl;
import ontology.resources.ISCB_Resource;

/**
 *
 * @author ghh
 */
public class ResourceDetailPane extends javax.swing.JPanel {

    public ISCB_Resource res;
    public ResourceTablePane parent;

    public static void main(String[] args) {
        ELearnerModelImpl emi = new ELearnerModelImpl();
        ISCB_Resource resource = emi.getEResource("rid000511");
        javax.swing.JFrame f = new javax.swing.JFrame();
        ResourceDetailPane rt = new ResourceDetailPane(new ResourceTablePane(), resource);
        f.add(rt);
        f.pack();
        f.setVisible(true);
    }

    /** Creates new form ResourceDetailPane */
    public ResourceDetailPane(ResourceTablePane parent, ISCB_Resource res) {
        this.res = res;
        this.parent = parent;
        initComponents();
        resourcename.setText(res.getName());
        resourcelink.setText(res.getFileLocation());
        mediatype.setText(res.getResourceType());
        String des = res.getResourceDescription();
//        char[] c = des.toCharArray();
//        StringBuilder sb = new StringBuilder();
//        for (int i = 0; i < c.length; i++) {
//            if ((i / 12 * 12 - i) == 0 && i != 0) {
//                sb.append("\n");
//            }
//            sb.append(c[i]);
//        }
//        description.setText(sb.toString());
        description.setText(des);
        System.out.println("des:" + des);
        difficulty.setText(res.getDifficulty());
        apptype.setText(res.getAppType());
    }

    public void setResourceLink(String label) {
        resourcelink.setText(label);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        backbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        resourcename = new javax.swing.JLabel();
        apptype = new javax.swing.JLabel();
        mediatype = new javax.swing.JLabel();
        difficulty = new javax.swing.JLabel();
        resourcelink = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "资源详情", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        setPreferredSize(new java.awt.Dimension(300, 350));

        jLabel1.setText("资源名称：");
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setRequestFocusEnabled(false);

        jLabel2.setText("资源应用类型：");
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setRequestFocusEnabled(false);

        jLabel3.setText("资源媒体类型：");
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setRequestFocusEnabled(false);

        jLabel4.setText("资源链接：");
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setRequestFocusEnabled(false);

        jLabel5.setText("资源难易度：");
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setRequestFocusEnabled(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        description.setColumns(20);
        description.setRows(5);
        description.setName("description"); // NOI18N
        jScrollPane1.setViewportView(description);

        backbutton.setText("返回");
        backbutton.setName("backbutton"); // NOI18N
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });

        jLabel6.setText("资源描述：");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setRequestFocusEnabled(false);

        resourcename.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resourcename.setName("resourcename"); // NOI18N

        apptype.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        apptype.setName("apptype"); // NOI18N

        mediatype.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mediatype.setName("mediatype"); // NOI18N

        difficulty.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        difficulty.setName("difficulty"); // NOI18N

        resourcelink.setBackground(new java.awt.Color(255, 255, 255));
        resourcelink.setForeground(new java.awt.Color(0, 0, 255));
        resourcelink.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resourcelink.setName("resourcelink"); // NOI18N
        resourcelink.setOpaque(true);
        resourcelink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resourcelinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resourcelinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resourcelinkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apptype, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(resourcename, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(difficulty, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(resourcelink, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(mediatype, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addComponent(backbutton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(backbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resourcename, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apptype, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediatype, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(difficulty, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resourcelink, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("资源名称:");
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        parent.goBackToTablePane();
    }//GEN-LAST:event_backbuttonMouseClicked

    private void resourcelinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resourcelinkMouseClicked
        if (resourcelink != null && evt.getClickCount() == 1) {
            String url = resourcelink.getText();
            System.out.println("url:" + url);
            WebOperation.viewResourceBroswer(url, res.getRid(), res.getIsLearntResult());
        }
    }//GEN-LAST:event_resourcelinkMouseClicked

    private void resourcelinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resourcelinkMouseEntered
        // TODO add your handling code here:
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_resourcelinkMouseEntered

    private void resourcelinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resourcelinkMouseExited
        // TODO add your handling code here:
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_resourcelinkMouseExited
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apptype;
    private javax.swing.JButton backbutton;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel difficulty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mediatype;
    private javax.swing.JLabel resourcelink;
    private javax.swing.JLabel resourcename;
    // End of variables declaration//GEN-END:variables
}
