/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddLPInterestItemPane.java
 *
 * Created on 2011-1-6, 10:43:19
 */
package lp.display;

import java.awt.event.MouseEvent;

/**
 *
 * @author william
 */
public class AddLPInterestItemPane extends javax.swing.JPanel implements java.awt.event.MouseListener {

    public static void main(String[] args) {
        jena.impl.ELearnerModelImpl emi = new jena.impl.ELearnerModelImpl(new java.io.File("test\\owl\\conceptsAndresource_RDF-XML.owl"));
        ontology.people.ELearner el = emi.getELearner("el001");
        //java.util.ArrayList<ontology.EInterest> interests = emi.getEInterests(el);
        java.util.ArrayList<ontology.EConcept> concepts = jena.ELearnerReasoner.getRecommendEConcepts_1(emi.getOntModel(), el);
        // System.out.println(interests);
        javax.swing.JFrame frame = new javax.swing.JFrame();
        // LPListPane lppane = new LPListPane(interests);
        javax.swing.JPanel pane = new javax.swing.JPanel();
        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        pane.setLayout(new javax.swing.BoxLayout(pane, javax.swing.BoxLayout.Y_AXIS));
        for (int i = 0; i < concepts.size(); i++) {
            AddLPInterestItemPane p = new AddLPInterestItemPane(concepts.get(i));
            pane.add(p);
        }
        frame.add(pane);
        frame.pack();
        frame.setVisible(true);
    }

    /** Creates new form AddLPInterestItemPane */
    public AddLPInterestItemPane() {
        initComponents();
        jLabel3.setText("");
        jLabel1.setText(concept.getCid());
        jLabel2.setText(concept.getName());
        addMouseListener(this);
    }

    public AddLPInterestItemPane(ontology.EConcept concept) {
        this.concept = concept;
        initComponents();
        jLabel3.setText("");
       jLabel1.setText(concept.getCid());
        jLabel2.setText(concept.getName());
        addMouseListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(321, 32));

        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("jLabel2");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("添加");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    public ontology.EConcept concept;

    @Override
    public void mouseClicked(MouseEvent e) {
        System.out.println("add Interest " + concept);
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        jLabel3.setText("添加");
    }

    @Override
    public void mouseExited(MouseEvent e) {
        jLabel3.setText("");
    }
}
