/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResourceTablePane.java
 *
 * Created on 2011-1-10, 22:16:11
 */
package lp.display;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import jena.impl.ELearnerModelImpl;
import ontology.resources.ISCB_Resource;

/**
 *
 * @author william
 */
public class ResourceTablePane extends javax.swing.JPanel {

    public static void main(String[] args) {
        ELearnerModelImpl emi = new ELearnerModelImpl();
        ArrayList<ISCB_Resource> res = emi.getEResourcesByEConcept(emi.getEConcept("cid1"));
        System.out.println("res size" + res.size());
        JFrame f = new JFrame();
        ResourceTablePane rt = new ResourceTablePane(res);
        f.add(rt);
        f.pack();
        f.setVisible(true);
    }

    /** Creates new form ResourceTablePane */
    public ResourceTablePane() {
        initComponents();
        myInit(new ArrayList<ISCB_Resource>());
    }

    public ResourceTablePane(ArrayList<ISCB_Resource> res) {
        initComponents();
        myInit(res);
    }

    private void myInit(ArrayList<ISCB_Resource> res) {
        resourceTable = new ResourceTable(res);
        jScrollPane1.setViewportView(resourceTable);
        jButton1.setEnabled(false);
    }

    public void updateResources(ArrayList<ISCB_Resource> res) {
        resourceTable.updateRes(res);
    }
    public ResourceTable resourceTable;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        jButton1.setText("上一页");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastPageClicked(evt);
            }
        });

        jButton2.setText("下一页");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPageClicked(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addContainerGap(74, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lastPageClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastPageClicked
        resourceTable.lastPage();
        if (resourceTable.currentPage == 0) {
            jButton1.setEnabled(false);
        }
        if (resourceTable.currentPage < resourceTable.pages - 1) {
            jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_lastPageClicked

    private void nextPageClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPageClicked
        resourceTable.nextPage();
        if (resourceTable.currentPage == resourceTable.pages - 1) {
            jButton2.setEnabled(false);
        }
        if (resourceTable.currentPage > 0) {
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_nextPageClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
