/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NavigatorConceptFinishPane.java
 *
 * Created on 2011-3-5, 15:29:46
 */

package lp.navigator;

import exception.jena.IndividualExistException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lp.LPApp;
import ontology.EConcept;
import ontology.EInterest;
import ontology.EPerformance;
import ontology.people.ELearner;

/**
 *
 * @author ghh
 */
public class NavigatorConceptFinishPane extends javax.swing.JPanel {
    public  ArrayList<EPerformance> performanceNodes = new ArrayList<EPerformance>();
    private NavigatorDialog parent;

    /** Creates new form NavigatorConceptFinishPane */
    public NavigatorConceptFinishPane(ArrayList<EPerformance> selectedNodes,NavigatorDialog parent) {
        this.parent = parent;
        parent.setTitle("初始化向导：确认正在学习的知识点");
        this.performanceNodes = selectedNodes;
        initComponents();

        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();

        for (int index = model.getRowCount() - 1; index >= 0; index--) {
            model.removeRow(index);
        }

        for (int i=0;i<performanceNodes.size();i++)
        {
            EPerformance temp = performanceNodes.get(i);
            String cid = temp.getConcept().getCid();
            EConcept ec = LPApp.lpModel.getEConcept(cid);
            //String interestId = this.interestNodes.get(i).getId();
            String cname = ec.getName();
          //  float value = temp.getValue();
          //  Object[] oa = {cid,cname,value};
            Object[] oa = {cid,cname};
            model.addRow(oa);
        }
        jTable1.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("您添加了学习中的知识点：");
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "知识点"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jButton3.setLabel("上一步");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("完成");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4finishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        parent.setPrevious();
       
        performanceNodes = new ArrayList<EPerformance>();
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        for (int index = model.getRowCount() - 1; index >= 0; index--) {
            model.removeRow(index);
        }
        jTable1.updateUI();

        //parent.nodes = new ArrayList<EInterest>();
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4finishActionPerformed
     /*   DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        int row = model.getRowCount();
        System.out.println(row);
        for (int i =0;i<row;i++) {
            String cid = model.getValueAt(i, 0).toString();
            EConcept ec = LPApp.lpModel.getEConcept(cid);
            //float value = Float.parseFloat(model.getValueAt(i, 2).toString());
            ELearner el = LPApp.getApplication().user.learner;
            EPerformance ep = LPApp.lpModel.getEPerformance(el, ec);
            //ep.setValue(value);
        }
        */
        // parent.setVisible(false);
        // parent.dispose();
         parent.nodesP = performanceNodes;
         parent.setNext();
         parent.setTitle("用户使用向导");

         //将感兴趣的知识点和学习中的知识点写入model
         for(int i = 0; i <parent.nodes.size();i++)
         {
             EInterest ei = parent.nodes.get(i);
            try {
                LPApp.lpModel.addEInterest(ei);
            } catch (IndividualExistException ex) {
                Logger.getLogger(NavigatorConceptFinishPane.class.getName()).log(Level.SEVERE, null, ex);
            }
         }

          for(int i = 0; i <parent.nodesP.size();i++)
         {
             EPerformance ep = parent.nodesP.get(i);
            try {
                LPApp.lpModel.addEPerfomance(ep);
            } catch (IndividualExistException ex) {
                Logger.getLogger(NavigatorConceptFinishPane.class.getName()).log(Level.SEVERE, null, ex);
            }
           
         }
         
    }//GEN-LAST:event_jButton4finishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
