/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminOperatorPane.java
 *
 * Created on 2011-4-25, 9:24:12
 */
package lp.admin;

import exception.jena.IndividualNotExistException;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import jena.OwlOperation;
import jena.impl.ELearnerModelImpl;
import jena.impl.OwlUpdate;
import lp.admin.ConceptDisplayPanelForGoal;
import lp.admin.ConceptDisplayPanelForRes;
import lp.admin.ConceptSelectPanel;
import lp.admin.ConceptSelectPanelForGoal;
import lp.admin.ConceptSelectPanelForRes;
import ontology.EConcept;
import ontology.EGoal;
import ontology.resources.ISCB_Resource;
import org.w3c.dom.Element;
import util.Constant;

/**
 *
 * @author William Ma <williamma.wm@gmail.com>
 */
public class AdminOperatorPane extends javax.swing.JPanel {

    /** Creates new form AdminOperatorPane */
    public AdminOperatorPane() {
        jComboBox3Boolean = false;
        jComboBox5Boolean = false;
        // emi = LPApp.lpModel;
        emi = new ELearnerModelImpl();
        ou = new OwlUpdate(emi, null);
        initComponents();
        //init the value of the compononets
        myInitComponents();
        // jTextField5.addActionListener(jComboBox1).addActionListener(new IdCheckListener(IdCheckListener.ADD_CONCEPT_ID,emi));
        initConceptPane();

    }

    private void myInitComponents() {
        //init add concept panel
        icon_yes = new javax.swing.ImageIcon("src/lp/admin/icon_yes.png");
        icon_no = new javax.swing.ImageIcon("src/lp/admin/icon_no.png");
        jTextField5.setText("");
        jTextField7.setText("");
        jTextField10.setText("");
        jLabel7.setIcon(icon_no);
        jLabel7.setText("no");
        jLabel20.setIcon(icon_no);
        jLabel20.setText("no");
        jLabel23.setIcon(icon_no);
        jLabel23.setText("no");
        String[] aptype = Constant.ERESOURCE_APPLICATION_TYPES_CN;
        jComboBox7.removeAllItems();
        for (int i = 1; i < aptype.length; i++) {
            jComboBox7.addItem(aptype[i]);
        }
        String[] metype = Constant.ERESOURCE_MEDIA_TYPES;
        jComboBox8.removeAllItems();
        for (int i = 1; i < metype.length; i++) {
            jComboBox8.addItem(metype[i]);
        }
        clearData();
    }

    private void clearData() {
        //add Concept Panel
        jLabel15.setText("");
        jTextField6.setText("");
        jLabel24.setText("");
        jLabel28.setText("");
        //add Resource Panel
        jLabel26.setText("");
        jLabel25.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextArea1.setText("");
        jComboBox7.setSelectedIndex(0);
        jComboBox8.setSelectedIndex(0);
        jComboBox9.setSelectedIndex(0);
        //add Goal Panel
        jTextField11.setText("");
        jLabel32.setText("");
        jLabel27.setText("");
    }
    private ELearnerModelImpl emi;
    private OwlUpdate ou;
    private HashSet<EGoal> goals;
    private HashSet<EConcept> concepts;
    private HashSet<ISCB_Resource> resources;
    //
    private ImageIcon icon_yes;
    private ImageIcon icon_no;
    private boolean jComboBox3Boolean;
    private boolean jComboBox5Boolean;

    private void initConceptPane() {

        //resource panel
        ConceptSelectPanel c1 = new ConceptSelectPanelForRes();

        //edit goal panel
        jComboBox3.removeAllItems();
        ArrayList<EGoal> goals = emi.getAllEGoals();
        for (EGoal goal : goals) {
            jComboBox3.addItem(goal);
        }
        jComboBox3Boolean = true;
        jComboBox3.setSelectedIndex(0);

        jComboBox5.removeAllItems();
        HashSet<ISCB_Resource> res = emi.getAllEReousrcesWithLeafConcept();
        //HashSet<ISCB_Resource> res = emi.getAllEResources();
        for (ISCB_Resource r : res) {
            jComboBox5.addItem(r);
        }
        jComboBox5Boolean = true;
        jComboBox5.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();

        jButton2.setText("保存本体");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveModelAction(evt);
            }
        });

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jLabel15.setText("jLabel15");
        jLabel15.setName("jLabel15"); // NOI18N

        jButton1.setText("添加知识点");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConceptAction(evt);
            }
        });

        jLabel24.setText("jLabel24");
        jLabel24.setName("jLabel24"); // NOI18N

        jButton5.setText("更新知识点");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateConceptAction(evt);
            }
        });

        jButton6.setText("删除知识点");
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeConceptAction(evt);
            }
        });

        jLabel6.setText("知识点ID：");
        jLabel6.setName("jLabel6"); // NOI18N

        jTextField5.setText("jTextField5");
        jTextField5.setName("jTextField5"); // NOI18N
        jTextField5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                EConceptIdChangedCheck(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel7.setText("j07");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(27, 27));

        jTextField6.setText("jTextField6");
        jTextField6.setName("jTextField6"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "初级", "中级", "高级" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jLabel11.setText("知识点名称：");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel4.setText("知识点难易度：");
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(38, 38, 38)
                        .addComponent(jButton5)
                        .addGap(38, 38, 38)
                        .addComponent(jButton6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addGap(403, 403, 403))
        );

        jTabbedPane1.addTab("增删知识点", jPanel3);

        jPanel5.setName("jPanel5"); // NOI18N

        jLabel16.setText("资源ID");
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("资源名称");
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setText("资源连接");
        jLabel18.setName("jLabel18"); // NOI18N

        jTextField8.setText("jTextField8");
        jTextField8.setName("jTextField8"); // NOI18N

        jTextField7.setText("jTextField7");
        jTextField7.setName("jTextField7"); // NOI18N
        jTextField7.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                EResourceIdChangedCheck(evt);
            }
        });

        jTextField9.setText("jTextField9");
        jTextField9.setName("jTextField9"); // NOI18N

        jLabel19.setText("资源描述");
        jLabel19.setName("jLabel19"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jLabel20.setText("j20");
        jLabel20.setName("jLabel20"); // NOI18N
        jLabel20.setPreferredSize(new java.awt.Dimension(27, 27));

        jButton3.setText("添加资源");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResAction(evt);
            }
        });

        jLabel25.setText("jLabel25");
        jLabel25.setName("jLabel25"); // NOI18N

        jLabel26.setText("jLabel26");
        jLabel26.setName("jLabel26"); // NOI18N

        jButton4.setText("更新资源");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateResAction(evt);
            }
        });

        jLabel29.setText("资源应用类型：");
        jLabel29.setName("jLabel29"); // NOI18N

        jLabel30.setText("资源媒体类型：");
        jLabel30.setName("jLabel30"); // NOI18N

        jButton7.setText("删除资源");
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeResAction(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox7.setName("jComboBox7"); // NOI18N

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox8.setName("jComboBox8"); // NOI18N

        jLabel31.setText("资源难易度：");
        jLabel31.setName("jLabel31"); // NOI18N

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "初级", "中级", "高级" }));
        jComboBox9.setName("jComboBox9"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)))
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel26)))
                        .addGap(635, 635, 635))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addContainerGap(527, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addContainerGap(746, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("增删资源", jPanel5);

        jPanel7.setName("jPanel7"); // NOI18N

        jLabel21.setText("目标ID");
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setText("目标名称");
        jLabel22.setName("jLabel22"); // NOI18N

        jTextField10.setText("jTextField10");
        jTextField10.setName("jTextField10"); // NOI18N
        jTextField10.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                EGoalIdChangedCheck(evt);
            }
        });

        jTextField11.setText("jTextField11");
        jTextField11.setName("jTextField11"); // NOI18N

        jLabel23.setText("j23");
        jLabel23.setName("jLabel23"); // NOI18N
        jLabel23.setPreferredSize(new java.awt.Dimension(27, 27));

        jLabel27.setText("jLabel27");
        jLabel27.setName("jLabel27"); // NOI18N

        jButton8.setText("添加目标");
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGoalAction(evt);
            }
        });

        jButton10.setText("更新目标");
        jButton10.setName("jButton10"); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGoalAction(evt);
            }
        });

        jButton12.setText("删除目标");
        jButton12.setName("jButton12"); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeGoalAction(evt);
            }
        });

        jLabel32.setText("jLabel32");
        jLabel32.setName("jLabel32"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField11)
                            .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(35, 35, 35)
                        .addComponent(jButton10)
                        .addGap(39, 39, 39)
                        .addComponent(jButton12))
                    .addComponent(jLabel32))
                .addGap(440, 440, 440))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton10)
                    .addComponent(jButton12))
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("增删目标", jPanel7);

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel8.setText("资源名称:");
        jLabel8.setName("jLabel8"); // NOI18N

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setName("jComboBox5"); // NOI18N
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResNameSelectedCheck(evt);
            }
        });

        jPanel10.setName("jPanel10"); // NOI18N
        jPanel10.setPreferredSize(new java.awt.Dimension(370, 400));

        jPanel11.setName("jPanel11"); // NOI18N
        jPanel11.setPreferredSize(new java.awt.Dimension(370, 400));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox5, 0, 697, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                .addGap(131, 131, 131))
        );

        jTabbedPane1.addTab("维护资源", jPanel2);

        jPanel4.setName("jPanel4"); // NOI18N

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setName("jComboBox3"); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goalNameSelectedCheck(evt);
            }
        });

        jLabel12.setText("目标名称：");
        jLabel12.setName("jLabel12"); // NOI18N

        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(370, 400));

        jPanel9.setName("jPanel9"); // NOI18N
        jPanel9.setPreferredSize(new java.awt.Dimension(370, 400));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("维护目标", jPanel4);

        jLabel28.setText("jLabel28");
        jLabel28.setName("jLabel28"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(311, 311, 311))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel28))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EConceptIdChangedCheck(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_EConceptIdChangedCheck
        // TODO add your handling code here:
        clearData();
        String content = jTextField5.getText().trim();
        if (content.equals("")) {
            jLabel15.setText("请输入Id，Id不能为空");
            jLabel7.setIcon(icon_no);
            jLabel7.setText("no");
        } else {
            boolean b = emi.containEConcept(content);
            if (b) {
                jLabel15.setText("ID已经存在于本体中，不能添加，可以更新知识点");
                EConcept con = emi.getEConcept(content);
                jTextField6.setText(con.getName());
                jComboBox1.setSelectedItem(con.getDifficulty());
                jLabel7.setIcon(icon_no);
                jLabel7.setText("no");
            } else {
                jLabel7.setIcon(icon_yes);
                jLabel7.setText("yes");
                jComboBox1.setSelectedIndex(0);
                jLabel15.setText("新Id无记录,可以添加知识点");
            }
        }
    }//GEN-LAST:event_EConceptIdChangedCheck

    private void addConceptAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConceptAction
        if (jLabel7.getText().trim().equals("yes")) {
            EConcept con = getEConceptFromAddConceptPanel();
            try {
                //System.out.println("con:"+con.getCid()+"\t"+con.getName()+"\t"+con.getDifficulty());
                emi.addEConcept(con);
                emi.addPropertyIsLeafConcept(con, true);
            } catch (IndividualNotExistException ex) {
                Logger.getLogger(AdminOperatorPane.class.getName()).log(Level.SEVERE, null, ex);
            }
            Element addCon = ou.getOperationElement(OwlUpdate.optypes[1], ou.createEConcpetElementByEConcpet(con));
            ou.addUpdate(addCon);
            jLabel24.setText("添加知识点成功.不要忘记点击“保存本体”哦");
        } else {
            jLabel24.setText("添加失败，请查看提示");
        }
    }//GEN-LAST:event_addConceptAction
    private EConcept getEConceptFromAddConceptPanel() {
        EConcept con = new EConcept(jTextField5.getText().trim());
        con.setName(jTextField6.getText().trim());
        con.setDifficulty(jComboBox1.getSelectedItem().toString());
        return con;
    }
    private void updateConceptAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateConceptAction
        if (jLabel7.getText().trim().equals("no")) {
            EConcept con = getEConceptFromAddConceptPanel();
            try {
                emi.updateEConcept(con);
            } catch (IndividualNotExistException ex) {
                Logger.getLogger(AdminOperatorPane.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabel24.setText("知识点ID不存在，无法更新");
        }
    }//GEN-LAST:event_updateConceptAction
    private void removeConceptAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeConceptAction
        // TODO add your handling code here:
        String cid = jTextField5.getText().trim();
        if (jLabel7.getText().trim().equals("no")) {
            boolean b = emi.removeEConcept(cid);
            if (b) {
                jLabel24.setText("知识点" + cid + "删除成功。不要忘记点击“保存本体”");
                Element removeIndi = ou.getOperationElement(OwlUpdate.optypes[OwlUpdate.REMOVEINDIVIDUAL], ou.createRemoveElement(cid));
                ou.addUpdate(removeIndi);
            } else {
                jLabel24.setText("知识点" + cid + "未删除成功");
            }
        } else {
            jLabel24.setText("知识点" + cid + "不存在");
        }
    }//GEN-LAST:event_removeConceptAction
    private void saveModelAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveModelAction
        try {
            File f = new File(Constant.OWLFile);
            OwlOperation.writeRdfFile(emi.getOntModel(), f, null);
            OwlOperation.writeOwlFileFromRdfFile(f, f);
            jLabel28.setText("成功保存本体到文件" + f.getPath());
            ou.initToFile("admin operation", "1.2");
            ou.writeToFile(ou.getDoc());
        } catch (IOException ex) {
            Logger.getLogger(AdminOperatorPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveModelAction
    private ISCB_Resource getEResourceFromAddResPanel() {
        ISCB_Resource res = new ISCB_Resource(jTextField7.getText().trim());
        res.setName(jTextField8.getText().trim());
        res.setFileLocation(jTextField9.getText().trim());
        res.setResourceDescription(jTextArea1.getText());
        res.setAppType(jComboBox7.getSelectedItem().toString());
        res.setResourceType(jComboBox8.getSelectedItem().toString());
        res.setDifficulty(jComboBox9.getSelectedItem().toString());
        return res;
    }
    private void EResourceIdChangedCheck(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_EResourceIdChangedCheck
        clearData();
        String rid = jTextField7.getText().trim();
        if (rid.equals("")) {
            jLabel20.setIcon(icon_no);
            jLabel20.setText("no");
            jLabel26.setText("请输入Id，Id不能为空");
        } else {
            boolean b = emi.containEResource(rid);
            if (b) {
                jLabel26.setText("ID已经存在于本体中，不能添加，可以更新资源");
                jLabel20.setIcon(icon_no);
                jLabel20.setText("no");
                ISCB_Resource res = emi.getEResource(rid);
                jTextField8.setText(res.getName());
                jTextField9.setText(res.getFileLocation());
                jTextArea1.setText(res.getResourceDescription());
                jComboBox9.setSelectedItem(res.getDifficulty());
                jComboBox7.setSelectedItem(res.getAppType());
                jComboBox8.setSelectedItem(res.getResourceType());
            } else {
                clearData();
                jLabel26.setText("新Id无记录,可以添加知识点");
                jLabel20.setIcon(icon_yes);
                jLabel20.setText("yes");
            }
        }
    }//GEN-LAST:event_EResourceIdChangedCheck
    private void addResAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResAction
        if (jLabel20.getText().trim().equals("yes")) {
            ISCB_Resource res = getEResourceFromAddResPanel();
            emi.addEResource(res);
            jLabel25.setText("添加资源成功.不要忘记点击“保存本体”哦");

            Element addRes = ou.getOperationElement(OwlUpdate.optypes[OwlUpdate.ADDERESOURCE], ou.createEResourceElementByEResource(res));
            ou.addUpdate(addRes);
        } else {
            jLabel25.setText("添加失败，请查看提示");
        }


    }//GEN-LAST:event_addResAction
    private void updateResAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateResAction
        if (jLabel20.getText().trim().equals("no")) {
            ISCB_Resource res = getEResourceFromAddResPanel();
            try {
                emi.updateEResource(res);
            } catch (IndividualNotExistException ex) {
                Logger.getLogger(AdminOperatorPane.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabel25.setText("资源不存在，无法更新");
        }
    }//GEN-LAST:event_updateResAction
    private void removeResAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeResAction
        String rid = jTextField7.getText().trim();
        if (jLabel20.getText().trim().equals("no")) {
            boolean b = emi.removeEResource(rid);
            if (b) {
                jLabel25.setText("资源" + rid + "删除成功。不要忘记点击“保存本体”");
                Element removeIndi = ou.getOperationElement(OwlUpdate.optypes[OwlUpdate.REMOVEINDIVIDUAL], ou.createRemoveElement(rid));
                ou.addUpdate(removeIndi);
            } else {
                jLabel25.setText("资源" + rid + "未删除成功。");
            }
        } else {
            jLabel25.setText("资源" + rid + "不存在");
        }
    }//GEN-LAST:event_removeResAction
    private EGoal getGoalFromAddGoalPanel() {
        EGoal goal = new EGoal();
        goal.setGid(jTextField10.getText().trim());
        goal.setName(jTextField11.getText().trim());
        return goal;
    }
    private void EGoalIdChangedCheck(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_EGoalIdChangedCheck
        // TODO add your handling code here:
        clearData();
        String gid = jTextField10.getText().trim();
        if (gid.equals("")) {
            jLabel23.setIcon(icon_no);
            jLabel23.setText("no");
            jLabel27.setText("请输入Id，Id不能为空");
        } else {
            boolean b = emi.containEGoal(gid);
            if (b) {
                jLabel27.setText("ID已经存在于本体中，不能添加，可以更新资源");
                jLabel23.setIcon(icon_no);
                jLabel23.setText("no");
                EGoal goal = emi.getEGoal(gid);
                jTextField11.setText(goal.getName());
            } else {
                clearData();
                jLabel27.setText("新Id无记录,可以添加知识点");
                jLabel23.setIcon(icon_yes);
                jLabel23.setText("yes");
            }
        }
    }//GEN-LAST:event_EGoalIdChangedCheck
    private void addGoalAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGoalAction
        if (jLabel23.getText().trim().equals("yes")) {
            EGoal goal = getGoalFromAddGoalPanel();
            emi.addEGoal(goal);
            jLabel27.setText("添加目标成功.不要忘记点击“保存本体”哦");
            Element addEGoal = ou.getOperationElement(OwlUpdate.optypes[OwlUpdate.ADDEGOAL], ou.createEGoalElementByEGoal(goal));
            ou.addUpdate(addEGoal);
        } else {
            jLabel27.setText("添加失败，请查看提示");
        }
    }//GEN-LAST:event_addGoalAction
    private void updateGoalAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGoalAction
        if (jLabel23.getText().trim().equals("no")) {
            EGoal goal = getGoalFromAddGoalPanel();
            emi.updateEGoal(goal);
            System.out.println("update goal successfully");
        } else {
            jLabel27.setText("目标不存在，无法更新");
        }
    }//GEN-LAST:event_updateGoalAction

    private void removeGoalAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeGoalAction
        String gid = jTextField10.getText().trim();
        if (jLabel23.getText().trim().equals("no")) {
            boolean b = emi.removeEGoal(gid);
            if (b) {
                jLabel27.setText("目标" + gid + "删除成功。不要忘记点击“保存本体”");
                Element removeIndi = ou.getOperationElement(OwlUpdate.optypes[OwlUpdate.REMOVEINDIVIDUAL], ou.createRemoveElement(gid));
                ou.addUpdate(removeIndi);
            } else {
                jLabel27.setText("目标" + gid + "未删除成功。");
            }
        } else {
            jLabel27.setText("目标" + gid + "不存在");
        }
    }//GEN-LAST:event_removeGoalAction

    private void goalNameSelectedCheck(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goalNameSelectedCheck
        // TODO add your handling code here:
        updateEditGoalPanel();
    }//GEN-LAST:event_goalNameSelectedCheck

    private void ResNameSelectedCheck(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResNameSelectedCheck
        // TODO add your handling code here:
        updateEditResPanel();
    }//GEN-LAST:event_ResNameSelectedCheck

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed
    public void updateEditGoalPanel() {
        if (jComboBox3Boolean) {
            EGoal goal = (EGoal) jComboBox3.getSelectedItem();
            HashSet restCons = emi.getAllLeafEConcepts();
            HashSet cons = emi.getEConceptsByGoal(goal);
            restCons.removeAll(cons);
            ConceptDisplayPanelForGoal g_c1 = new ConceptDisplayPanelForGoal(emi, cons);
            ConceptSelectPanelForGoal g_c2 = new ConceptSelectPanelForGoal(emi, restCons);
            g_c2.setGoal(goal);
            g_c1.setGoal(goal);
            g_c1.adminPanel = this;
            g_c2.adminPanel = this;
            jPanel8.removeAll();
            jPanel9.removeAll();
            jPanel8.add(g_c1);
            jPanel9.add(g_c2);
            jPanel8.updateUI();
            jPanel9.updateUI();
        }
    }

    public void updateEditResPanel() {
        if (jComboBox5Boolean) {
            ISCB_Resource res = (ISCB_Resource) jComboBox5.getSelectedItem();
            HashSet restCons = emi.getAllLeafEConcepts();
            //HashSet cons = emi.getEConcepts(res);
            HashSet cons = emi.getLeafConcepts(res);
            restCons.removeAll(cons);
            ConceptDisplayPanelForRes r_c1 = new ConceptDisplayPanelForRes(emi, cons);
            ConceptSelectPanelForRes r_c2 = new ConceptSelectPanelForRes(emi, restCons);
            r_c2.setRes(res);
            r_c1.setRes(res);
            r_c1.adminPanel = this;
            r_c2.adminPanel = this;

            jPanel10.removeAll();
            jPanel11.removeAll();
            jPanel10.add(r_c1);
            jPanel11.add(r_c2);
            jPanel10.updateUI();
            jPanel11.updateUI();
        }
    }

    public void getPropertyContainsConcept(String optype,String gid, String cid) {
        Element element = ou.getObjectPropertyOperationElement(optype, gid, "contain_concepts", cid);
        ou.addUpdate(element);
    }

    public void getPropertyIsResourceOfC(String optype,String rid, String cid) {
        Element element = ou.getObjectPropertyOperationElement(optype, rid, "is_resource_of_C", cid);
        Element element2 = ou.getObjectPropertyOperationElement(optype, cid, "inverse_of_is_resource_of_C", rid);

        ou.addUpdate(element);
        ou.addUpdate(element2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        javax.swing.JFrame f = new javax.swing.JFrame();
        f.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        AdminOperatorPane pane = new AdminOperatorPane();
        f.add(pane);
        f.pack();
        f.setVisible(true);
    }
}
