/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConceptSelectPanel.java
 *
 * Created on 2011-5-20, 13:54:07
 */
package lp.admin;

import java.util.HashSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jena.impl.ELearnerModelImpl;
import ontology.EConcept;

/**
 *
 * @author student
 */
public class ConceptSelectPanel extends javax.swing.JPanel {

    /** Creates new form ConceptSelectPanel */
    public ConceptSelectPanel() {
        initComponents();
        emi = new ELearnerModelImpl();
        cons = emi.getAllLeafEConcepts();
        allCons = emi.getAllLeafEConcepts();
//        cons = new ArrayList<EConcept> ();
        jTextField1.setText("");
        updateData();
    }

    public ConceptSelectPanel(ELearnerModelImpl emi, HashSet<EConcept> cons) {
        initComponents();
        this.emi = emi;
        this.cons = cons;
        allCons = new HashSet<EConcept>();
        for (EConcept con : cons) {
            allCons.add(con);
        }
//        cons = new ArrayList<EConcept> ();
        jTextField1.setText("");
        updateData();
    }

    public AdminOperatorPane adminPanel;

    public static void main(String[] args) {
        javax.swing.JFrame f = new javax.swing.JFrame();
        f.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        ConceptSelectPanel pane = new ConceptSelectPanel();
        f.add(pane);
        f.pack();
        f.setVisible(true);
    }
    protected HashSet<EConcept> cons;
    protected HashSet<EConcept> allCons;

    protected JTable getTable() {
        return jTable1;
    }
    protected ELearnerModelImpl emi;

    protected void updateData() {
        DefaultTableModel tm = getTableModel();
        for (int index = tm.getRowCount() - 1; index >= 0; index--) {
            tm.removeRow(index);
        }
        for (EConcept con : cons) {
            Object[] o = {con.getCid(), con.getName(), con.getDifficulty()};
            tm.addRow(o);
        }
        jLabel2.setText("共" + cons.size() + "个知识点");
    }

    protected void clearData() {
        DefaultTableModel tm = getTableModel();
        for (int index = tm.getRowCount() - 1; index >= 0; index--) {
            tm.removeRow(index);
        }
    }

    protected DefaultTableModel getTableModel() {
        return (DefaultTableModel) jTable1.getModel();
    }

    public void buttonAction() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("知识点查询：");
        jLabel1.setName("jLabel1"); // NOI18N

        jTextField1.setText("jTextField1");
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                conceptSearchCheck(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "知识点ID", "知识点名称", "难易度"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("控制按钮");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("知识点难易度:");
        jLabel3.setName("jLabel3"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "全部", "初级", "中级", "高级", " " }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jLabel2.setText("jLabel2");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        buttonAction();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void conceptSearchCheck(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_conceptSearchCheck
        // TODO add your handling code here:
        cons.clear();
        boolean b = false;

        String diff = jComboBox1.getSelectedItem().toString().trim();
        if (diff.equals("全部")) {
            b = true;
        }
        if (jTextField1.getText().trim().equals("")) {
            for (EConcept con : allCons) {
                if (b || con.getDifficulty().equals(diff)) {
                    cons.add(con);
                }
            }
        } else {
            for (EConcept con : allCons) {
                if (con.getName().startsWith(jTextField1.getText().trim())) {
                    if (b || con.getDifficulty().equals(diff)) {
                        cons.add(con);
                    }
                }
            }
        }
        updateData();
    }//GEN-LAST:event_conceptSearchCheck
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
