/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableTemplate.java
 *
 * Created on 2011-5-3, 22:17:43
 */
package lp.admin;

import java.awt.Point;
import java.awt.event.MouseListener;
import java.util.HashSet;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author William Ma <williamma.wm@gmail.com>
 */
public class TableTemplate extends javax.swing.JPanel {

    /** Creates new form TableTemplate */
    public TableTemplate() {
        initComponents();
        data = new HashSet<Object>();
        initButton();
        initData();
        initTable();
    }

    public TableTemplate(HashSet<Object> data) {
        initComponents();
        this.data = data;
        initButton();
        initData();
        initTable();
    }

    public void initTable() {
        jTable1.setRowSelectionInterval(0, 0);
        if (rowPerPage < data.size()) {
            jButton2.setEnabled(true);
        } else {
            jButton2.setEnabled(false);
        }
        jButton1.setEnabled(false);
        jLabel1.setText(getLabel());
    }

    protected void initButton() {
        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastPageAction(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPageAction(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDataAction(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickedOnTableAction(evt);
            }
        });
    }
    protected int rowPerPage = 10;
    protected int currentPage = 1;
    protected HashSet<Object> data;
    protected DefaultTableModel tableModel;

    protected void initData() {
    }

    protected void lastPageAction(java.awt.event.ActionEvent evt) {
        if (!jButton2.isEnabled()) {
            jButton2.setEnabled(true);
        }
        currentPage--;
        updateData(currentPage, data);
        if (currentPage == 1) {
            jButton1.setEnabled(false);
        }
        System.out.println("last current:" + currentPage);
        jLabel1.setText(getLabel());
    }

    protected void nextPageAction(java.awt.event.ActionEvent evt) {
        if (!jButton1.isEnabled()) {
            jButton1.setEnabled(true);
        }
        currentPage++;
        updateData(currentPage, data);
        if (currentPage * rowPerPage > data.size()) {
            jButton2.setEnabled(false);
        }
        System.out.println("current:" + +currentPage);
        jLabel1.setText(getLabel());
    }

    protected void mouseClickedOnTableAction(java.awt.event.MouseEvent e) {
        if (e.getComponent().isEnabled() && e.getClickCount() == 1) {
            Point p = e.getPoint();
            int row = jTable1.rowAtPoint(p);
            jTable1.setRowSelectionInterval(row, row);
        }
        jLabel1.setText(getLabel());

    }

    protected String getLabel() {
        String s = (jTable1.getSelectedRow() + (currentPage - 1) * rowPerPage + 1) + "/" + data.size();
        return s;
    }

    protected void updateData(int page, HashSet<Object> data) {
    }

    protected void removeDataAction(java.awt.event.ActionEvent evt) {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("Title 1");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Title 2");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Title 3");

        jButton1.setText("上一页");
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setText("下一页");
        jButton2.setName("jButton2"); // NOI18N

        jLabel1.setText("条目数目");
        jLabel1.setName("jLabel1"); // NOI18N

        jButton3.setText("删除所选条目");
        jButton3.setName("jButton3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(39, 39, 39))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    public void setResourceModel() {
        tableModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String[]{
                    "资源ID", "资源名称", "资源难易度"
                }) {

            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };
    }

    public void setConceptModel() {
        tableModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String[]{
                    "知识点ID", "知识点名称", "知识点难易"
                }) {

            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };
    }
    protected void clearTableModel(){
          for (int index = tableModel.getRowCount() - 1; index >= 0; index--) {
            tableModel.removeRow(index);
        }
    }
    public int getCurrentPage() {
        return currentPage;
    }

    public void setCurrentPage(int currentPage) {
        this.currentPage = currentPage;
    }

    public HashSet<Object> getData() {
        return data;
    }

    public void setData(HashSet<Object> data) {
        this.data = data;
    }

    public int getRowPerPage() {
        return rowPerPage;
    }

    public void setRowPerPage(int rowPerPage) {
        this.rowPerPage = rowPerPage;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    protected javax.swing.JButton jButton3;
    protected javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
