/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConceptPane.java
 *
 * Created on 2011-1-9, 16:51:23
 */
package lp;

import exception.jena.IndividualExistException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import lp.eresource.ResourceTablePane;
import ontology.EConcept;
import ontology.EPerformance;
import ontology.people.ELearner;
import ontology.resources.ISCB_Resource;

/**
 *
 * @author student
 */
public class ConceptPane extends javax.swing.JPanel {

    public EConcept cdec = null;

    /** Creates new form ConceptPane */
    public ConceptPane() {
        initComponents();
        resourceTablePane = new ResourceTablePane(new ArrayList<ISCB_Resource>());
        jScrollPane1.setViewportView(resourceTablePane);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        conceptName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uriLabel = new javax.swing.JLabel();
        learnBtn = new javax.swing.JButton();
        examBtn = new javax.swing.JButton();
        examScore = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "概念", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        setDoubleBuffered(false);

        jLabel1.setText("知识点：");
        jLabel1.setName("jLabel1"); // NOI18N

        conceptName.setText("概念名");
        conceptName.setName("conceptName"); // NOI18N

        jLabel2.setText("URI:");
        jLabel2.setName("jLabel2"); // NOI18N

        uriLabel.setText("URI");
        uriLabel.setName("uriLabel"); // NOI18N

        learnBtn.setText("学习它");
        learnBtn.setName("learnBtn"); // NOI18N
        learnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnBtnActionPerformed(evt);
            }
        });

        examBtn.setText("学习效果评估");
        examBtn.setEnabled(false);
        examBtn.setName("examBtn"); // NOI18N
        examBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examBtnActionPerformed(evt);
            }
        });

        examScore.setName("examScore"); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(160, 160, 160), 1, true), "相关资源", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14))); // NOI18N
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uriLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(conceptName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(learnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(examBtn)
                        .addGap(51, 51, 51)
                        .addComponent(examScore, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(conceptName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(uriLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(learnBtn)
                        .addComponent(examBtn))
                    .addComponent(examScore, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void learnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learnBtnActionPerformed
        EPerformance ep = LPApp.lpModel.getEPerformance(new ELearner(LPApp.getApplication().user.username), cdec);
        if (ep == null) {
            ep = new EPerformance();
            ep.setValue(-1);
            ep.setConcept(cdec);
            ep.setElearner(LPApp.getApplication().user.learner);
            ep.setId(LPApp.getApplication().user.learner.getId() + cdec.getCid() + "_p");
            ep.setDatetime(new Date(System.currentTimeMillis()));
            try {
                LPApp.lpModel.addEPerfomance(ep);
            } catch (IndividualExistException ex) {
                Logger.getLogger(ConceptDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.updateData();
        LPApp.lpLog.writeMessage("学习了知识点:"+cdec.getCid()+","+cdec.getName()+"\n");
}//GEN-LAST:event_learnBtnActionPerformed
    @Override
    public String toString() {
        return conceptName.getText() + "\t" + uriLabel.getText();
    }

    public void updateResouceTable(EConcept ec) {
        ArrayList<ISCB_Resource> ra = LPApp.lpModel.getEResourcesByEConcept(ec);
        resourceTablePane.updateResources(ra);
    }

    public void setConceptName(String name) {
        conceptName.setText(name);
    }

    public void setURIName(String uri) {
        uriLabel.setText(uri);
    }

    public void updateData() {
        if (cdec != null) {
            EPerformance ep = LPApp.lpModel.getEPerformance(new ELearner(LPApp.getApplication().user.username), cdec);
            this.examScore.setText("");
            if (ep != null) {
                if (ep.getValue() > -0.5) {
                    this.learnBtn.setText("已学过");
                    examScore.setVisible(true);
                    examScore.setText("成绩为" + ep.getValue());
                } else {
                    this.learnBtn.setText("正在学习");
                    examScore.setVisible(false);
                }
                this.learnBtn.setEnabled(false);
                this.examBtn.setEnabled(true);
            } else {
                learnBtn.setText("学习它");
                learnBtn.setEnabled(true);
                examBtn.setEnabled(false);
                examScore.setVisible(false);
            }
        }
    }

    @Override
    public void setVisible(boolean b) {
        if (b) {
            this.updateData();
        }
        super.setVisible(b);
    }
    private void examBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examBtnActionPerformed
        this.jScrollPane1.setViewportView(new RadarPanel());
}//GEN-LAST:event_examBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel conceptName;
    private javax.swing.JButton examBtn;
    private javax.swing.JLabel examScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton learnBtn;
    public javax.swing.JLabel uriLabel;
    // End of variables declaration//GEN-END:variables
    public ResourceTablePane resourceTablePane;
}
